### ISSUE TITLE
awesome-promises

### ISSUE THREAD

**Issue by sindresorhus** [mattdesl/promise-cookbook#5]
Maybe link up https://github.com/wbinnssmith/awesome-promises somewhere? It's a useful resource.

// @wbinnssmith

**Comment by wbinnssmith** [comment]
Since awesome-promises links here, it _could_ cause an infinite spiral of recursive awesomeness. Worth a try.

**Comment by mattdesl** [comment]
I approve. Been busy this week but would accept a pr. 🙌
